package_assets: off
package_path: assets-compiled
compress_assets: true
gzip_assets: false

javascripts:
  app:
    # vendor
    - public/js/vendor/jquery.effects.core.js
    - public/js/vendor/jquery.effects.fade.js
    - public/js/vendor/jquery.animate-enhanced.js
    - public/js/vendor/underscore.js
    - public/js/vendor/backbone.js
    # app
    - public/js/compiled/**/*.js

stylesheets:
  app:
    - public/css/compiled/app.css
